version: '2'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - APP_NAME=tic-tac-toe
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis  